=== estefaniapenide/lenguajes_marcas/Tema 3. XML/Ejercicios/biblioteca2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="biblioteca">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="libro" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
        <xs:sequence>
        <xs:element ref="titulo"/>
        <xs:element ref="autor" maxOccurs="5"/>
        <xs:element ref="año"/>
        <xs:element ref="editorial"/>
        </xs:sequence>
        <xs:attribute name="codigo" type="xs:string" use="required"/>
        </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="titulo" type="xs:string"/>
  <xs:element name="autor" type="xs:string"/>
  <xs:element name="año" type="xs:string"/>
  <xs:element name="editorial" type="xs:string"/>
</xs:schema>

=== estefaniapenide/lenguajes_marcas/Tema 3. XML/Ejercicios/biblioteca2.xml
<?xml version="1.0" encoding="UTF-8"?>
<biblioteca xsi:noNamespaceSchemaLocation="biblioteca2.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<libro codigo="114">
<titulo>Pequeña Historia de España</titulo>
<autor>Manuel Fernández Álvarez</autor>
<año>2008</año>
<editorial>Espasa</editorial>
</libro>
<libro codigo="345">
<titulo>El loco cuento de todos los cuentos</titulo>
<autor>Jose María Plaza</autor>
<año>2013</año>
<editorial>Santillana</editorial>
</libro>
</biblioteca>
