<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE lista_de_personas [
<!ELEMENT lista_de_personas (persona)+>
<!ELEMENT persona (nombre,fechanacimiento,telefono*,sexo?,numeroseguridadsocial?)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT fechanacimiento (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT sexo (#PCDATA)>
<!ELEMENT numeroseguridadsocial (#PCDATA)>
<!ATTLIST persona nacionalidad (española | inglesa | portuguesa) "española">
]>
<lista_de_personas>
<persona>
<nombre>Jose García</nombre>
<fechanacimiento>25/04/1984</fechanacimiento>
<telefono>12345612345</telefono>
<telefono>122432</telefono>
<sexo>Varón</sexo>
</persona>
<persona nacionalidad="inglesa">
<nombre>John</nombre>
<fechanacimiento>25/04/1984</fechanacimiento>
<telefono>123456</telefono>
<numeroseguridadsocial>1234567890</numeroseguridadsocial>
</persona>
</lista_de_personas>