<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE productos [
<!ELEMENT productos (raton|teclado)*>
<!ELEMENT raton (#PCDATA|codigo|descripcion)*>
<!ELEMENT teclado (codigo,descripcion,peso?)>
<!ELEMENT codigo (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT peso (#PCDATA)>
  ]>
  <productos>
  <raton>Prueba
  <codigo>R1</codigo>
  <descripcion>Ratón normalillo</descripcion>
  </raton>
  <raton>Prueba
  <codigo>R2</codigo>
  </raton>
  <teclado>
  <codigo>T1</codigo>
  <descripcion>Teclado normalillo</descripcion>
  <peso>200gr</peso>
  </teclado>
  <raton>Prueba
  <codigo>R2</codigo>
  </raton>
  <teclado>
  <codigo>T2</codigo>
  <descripcion>Teclado mejor que el T1</descripcion>
  </teclado>
  </productos>
